import { MetadataRoute } from 'next';

export const dynamic = 'force-static';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/admin/',
        '/_next/',
        '/out/',
        '/node_modules/',
        '/.git/',
        '/.next/',
        '/public/',
        '/src/',
        '/scripts/',
        '/automation/',
        '/migrations/',
        '/instance/',
        '/templates/',
        '/css/',
        '/country/',
        '/destination/',
        '/route/',
        '/hotel_near/',
        '/routes/',
        '/images/',
        '/data/',
        '/config/',
        '/blog/',
        '/creator/',
        '/flask_app.py',
        '/server.py',
        '/generate_*.py',
        '/research_*.py',
        '/detailed_research_*.py',
        '/add_route.py',
        '/requirements.txt',
        '/render.yaml',
        '/netlify.toml',
        '/next.config.js',
        '/next.config.ts',
        '/tailwind.config.ts',
        '/postcss.config.mjs',
        '/eslint.config.mjs',
        '/tsconfig.json',
        '/package.json',
        '/package-lock.json',
        '/.gitignore',
        '/README*.md',
        '/ESTADO_PROYECTO.md',
        '/DAILY_WORK_LOG.md',
        '/TODAY_SUMMARY.md',
        '/Infraestructura.md',
        '/PAGES_DETAILS.md',
        '/GOOGLE_MAPS_SETUP.md',
        '/env_example.txt',
        '/run_server.bat',
        '/update-data.bat',
        '/test*.html',
        '/test_google_maps.html',
        '/research_example_*.json',
        '/routes_to_research.csv',
        '/PHqJwXEBeW6HKOyio7bi0A== (1).csv',
        '/LE_Destinations.csv',
        '/destination_links.csv',
        '*.json',
        '*.csv',
        '*.py',
        '*.md',
        '*.txt',
        '*.bat',
        '*.html'
      ],
    },
    sitemap: 'https://mondoexplora.com/sitemap.xml',
    host: 'https://mondoexplora.com',
  };
}
